### ISSUE TITLE
Available in Maven Central?

### ISSUE THREAD

**Issue by binkley** [Addicticks/jTextTime#1]
I'm having trouble finding this dependency:

`com.addicticks.oss.jaxb:java8datetime:1.2.0`

Am I using the wrong one?

**Comment by addicticks-dev** [comment]
Apologies. The [README](https://github.com/Addicticks/jTextTime/blob/master/README.md) was incorrectly still pointing to the former location. Now [fixed](https://github.com/Addicticks/jTextTime/commit/ddc74eebb5896c1f457a2987f3e9a52d8bc6a85b).

You should use:

`com.addicticks.oss:jtexttime:<latest>
`

which currently means:

`com.addicticks.oss:jtexttime:1.2.0
`

Thank you for reporting.
