### ISSUE TITLE
Parsing of dateTime with hour 24 fails

### ISSUE THREAD

**Issue by jeichhorn** [Addicticks/jTextTime#4]
According to https://www.w3.org/TR/xmlschema-2/#dateTime the hour 24 is allowed if the minutes and seconds represented are zero.
When parsing "2022-02-28T24:00:00" I get the error that only the value 0-23 are allowed

**Comment by addicticks-dev** [comment]
Yes, you are right.

It is an unfortunate thing about the spec that it allows two values which means the same thing:

`2022-02-28T24:00:00` is exactly the same as `2022-03-01T00:00:00`.

I think this is one of those things that happens with specs: they sometimes have to simultaneously support different **conflicting cultural patterns**. My own culture would never use '24' for midnight but I bet there are cultures which do. The XSD spec authors decided to support both.  It is a mistake to try to accommodate both in the spec, if you ask me.

But it is in the spec. Let me think a day or two about the best fix.

**Comment by addicticks-dev** [comment]
Version `1.2.2` fixes this issue. There is now full support for parsing `24:00:00`.

The new version will be available in Maven Central when sync completes (within 10 min to 1 hour from now)
You can check  [here](https://repo1.maven.org/maven2/com/addicticks/oss/jtexttime/)

**Comment by addicticks-dev** [comment]
Added bullet point on this topic [in the wiki](https://github.com/Addicticks/jTexttime/wiki/JAXB-type-adapter-classes-for-java.time) (at the very bottom of page).
